stages:
  - build
  - push

variables:
  IMAGE_NAME: "registry.gitlab.com/yourusername/yourproject"
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME
