image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/yourusername/yourproject
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  COMPOSE_FILE: docker-compose.yml # Specify the Docker Compose file to be used

before_script:
  - apk add --no-cache docker-cli
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - cp .env.example .env # Ensure .env exists
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME . # Build Docker image
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME # Push to registry

deploy:
  stage: deploy
  only:
    - main # Only deploy on the main branch
  script:
    - apk add --no-cache docker-cli docker-compose # Install Docker CLI and Compose
    - cp .env.example .env # Ensure .env exists for Docker Compose
    - docker-compose --file $COMPOSE_FILE down # Bring down existing containers (if any)
    - docker-compose --file $COMPOSE_FILE pull # Pull latest images for containers
    - docker-compose --file $COMPOSE_FILE up -d --build # Rebuild and start containers in detached mode
