stages:
  - build
  - push

variables:
  IMAGE_NAME: "registry.gitlab.com/yourusername/yourproject"

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME
