image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/yourusername/yourproject
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache docker-cli
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

test:
  stage: test
  image: node:18
  before_script: []
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - cp .env.example .env # Ensure .env exists
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  only:
    - main
  script:
    - apk add --no-cache docker-cli docker-compose
    - cp .env.example .env # Ensure .env exists for Docker Compose
    - docker-compose --env-file .env down
    - docker-compose --env-file .env pull
    - docker-compose --env-file .env up -d --build
