image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/yourusername/yourproject
  DB_HOST: your-aws-rds-endpoint
  DB_USER: your_db_user
  DB_PASSWORD: your_db_password
  DB_NAME: your_db_name
  DB_PORT: 5432

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

test:
  stage: test
  image: node:18
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d --build
