version: "3.8"

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${PG_HOST}
      DB_USER: ${PG_USER}
      DB_PASSWORD: ${PG_PASSWORD}
      DB_NAME: ${PG_DATABASE}
      DB_PORT: ${PG_PORT}
    volumes:
      - ./.env:/app/.env # Make sure the .env file is available inside the container
    restart: always
